# -*- coding: utf-8 -*-
"""FINAL YEAR PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eHnQGVNAT6-MZjFxo8RfmAQjfE2VqgLh
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile

zip_path = "/content/drive/MyDrive/Images.zip"
extract_path = "/content/images"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Unzipped successfully ✅")

import os

folder = "/content/images"

print("Total images:", len(os.listdir(folder)))

import numpy as np
import os
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import random

tf.random.set_seed(42)
np.random.seed(42)
random.seed(42)

df = pd.read_csv("/content/drive/MyDrive/Brain Tumor.csv")

dataset_path = "/content/images"

print(df.head())

print(df.columns)

image_folder = "/content/images"

images = []
labels = []

for i in range(len(df)):
    img_name = df['Image'][i] + ".jpg"
    label = df['Class'][i]

    img_path = os.path.join(image_folder, img_name)

    if os.path.exists(img_path):
        img = load_img(img_path, target_size=(224, 224))
        img = img_to_array(img) / 255.0

        images.append(img)
        labels.append(label)

images = np.array(images)
labels = np.array(labels)

print("Images:", images.shape)
print("Labels:", labels.shape)

from sklearn.cluster import KMeans

flattened_images = images.reshape(images.shape[0], -1)

kmeans = KMeans(n_clusters=2, random_state=42)

cluster_labels = kmeans.fit_predict(flattened_images)

print("K-Means Clustering Applied Successfully")

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    images, labels, test_size=0.2, random_state=42
)

datagen = ImageDataGenerator(
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

datagen.fit(X_train)

from tensorflow.keras.applications import ResNet50

base_model = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)

for layer in base_model.layers[:-15]:
    layer.trainable = False

for layer in base_model.layers[-15:]:
    layer.trainable = True

from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.models import Model

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
output = Dense(1, activation='sigmoid')(x)

model = Model(inputs=base_model.input, outputs=output)

from tensorflow.keras.optimizers import Adam

model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

from tensorflow.keras.callbacks import ReduceLROnPlateau

lr_reduce = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.3,
    patience=2,
    min_lr=1e-6
)

checkpoint = ModelCheckpoint(
    "best_model.keras",
    monitor='val_accuracy',
    save_best_only=True
)

from tensorflow.keras.optimizers import Adam

model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    datagen.flow(X_train, y_train, batch_size=16),
    validation_data=(X_test, y_test),
    epochs=10,
    callbacks=[
        early_stop,
        lr_reduce,
        checkpoint])

from tensorflow.keras.models import load_model; model = load_model("/content/drive/MyDrive/best_model.keras")

loss, acc = model.evaluate(X_test, y_test)
print(f"Final Accuracy: {acc*100:.2f}%")
print(f"Final Loss: {loss:.4f}")

def fuzzy_decision(confidence):

    if confidence >= 0.85:
        category = "High Tumor Confidence"

    elif confidence >= 0.70:
        category = "Moderate Tumor Confidence"

    elif confidence >= 0.50:
        category = "Low Tumor Confidence"

    else:
        category = "Non-Tumor"

    return category

prediction = model.predict(X_test[:1])

confidence = float(prediction[0][0])
result = fuzzy_decision(confidence)

print("Prediction Confidence:", confidence)
print("Fuzzy Logic Result:", result)

from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

print(classification_report(y_test, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(5,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

train_acc = [0.8897, 0.8933, 0.8960, 0.8983, 0.9020, 0.9013]
val_acc = [0.8738, 0.9017, 0.9084, 0.8114, 0.8871, 0.8818]
plt.plot(train_acc, label='Train Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.legend()
plt.title("Accuracy Graph")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.show()

plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend()
plt.title("Loss Graph")
plt.show()

from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt
img_num = input("Enter image number (e.g., 1, 25, 300): ")
img_path = f"/content/images/Image{img_num}.jpg"
img = image.load_img(img_path, target_size=(224,224))
img_array = image.img_to_array(img)/255.0
img_array = np.expand_dims(img_array, axis=0)
prediction = model.predict(img_array)
confidence = prediction[0][0]
if confidence > 0.5:
    result = f"Tumor Detected ({confidence*100:.2f}%)"
else:
    result = f"No Tumor ({(1-confidence)*100:.2f}%)"
plt.imshow(img)
plt.axis('off')
plt.title(result)
plt.show()

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import cv2

from tensorflow.keras.preprocessing.image import load_img, img_to_array
image_number = input("Enter image number (e.g., 1, 14, 300): ")

img_path = f"/content/images/Image{image_number}.jpg"

print("Selected Image:", img_path)
img = load_img(img_path, target_size=(224,224))

img_array = img_to_array(img) / 255.0

img_array = np.expand_dims(img_array, axis=0)
grad_model = tf.keras.models.Model(
    [model.inputs],
    [
        model.get_layer("conv5_block3_out").output,
        model.output
    ]
)

with tf.GradientTape() as tape:

    conv_outputs, predictions = grad_model(img_array)

    loss = predictions[:,0]

grads = tape.gradient(loss, conv_outputs)

pooled_grads = tf.reduce_mean(grads, axis=(0,1,2))

conv_outputs = conv_outputs[0]
heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]

heatmap = tf.squeeze(heatmap)

heatmap = np.maximum(heatmap, 0)

heatmap = heatmap / np.max(heatmap)
original_img = cv2.imread(img_path)

original_img = cv2.resize(original_img, (224,224))
heatmap = cv2.resize(
    heatmap,
    (original_img.shape[1], original_img.shape[0])
)

heatmap = np.uint8(255 * heatmap)
heatmap = cv2.applyColorMap(
    heatmap,
    cv2.COLORMAP_JET
)
superimposed_img = heatmap * 0.4 + original_img
plt.figure(figsize=(6,6))

plt.imshow(
    cv2.cvtColor(
        np.uint8(superimposed_img),
        cv2.COLOR_BGR2RGB
    )
)

plt.axis('off')

plt.title("Grad-CAM Tumor Visualization")

plt.show()

